wordList = [
        "abacaxi", "elefante", "computador", "python", "programacao",
        "cachorro", "girafa", "praia", "oceano", "montanha",
        "futebol", "ginastica", "escola", "aventura", "bicicleta",
        "frutas", "verao", "inverno", "outono", "primavera",
        "televisao", "leitura", "internet", "telefone", "celular",
        "cachecol", "sorvete", "piano", "viagem", "banana",
        "paralelepipedo", "amizade", "feliz", "triste", "alegre",
        "felino", "guitarra", "esquilo", "malabarismo", "laboratorio",
        "algoritmo", "software", "hardware", "tecnologia", "pessoa",
        "carteira", "oculos", "sapato", "meia", "bonito",
        "feio", "simples", "complexo", "rapido", "lento",
        "maravilha", "maravilhoso", "espelho", "espelhado", "sol",
        "lua", "estrela", "universo", "galaxia", "constelacao",
        "aleatorio", "vibrante", "profundo", "fantastico", "incrivel",
        "energia", "positivo", "negativo", "centro", "norte",
        "sul", "leste", "oeste", "pintura", "escultura",
        "literatura", "musica", "filme", "teatro", "circo",
        "magico", "hipopotamo", "tigre", "leao", "girassol",
        "colina", "riacho", "cachoeira", "selva", "deserto",
        "eletronico", "exotico", "fascinante", "harmonia", "serenidade",
        "jardim", "orquidea", "floresta", "montanha-russa", "gargalhada",
        "sabedoria", "mistico", "chocolate", "divertido", "saboroso",
        "papel", "caneta", "lapiseira", "notebook", "relaxante",
        "confiante", "esportivo", "imaginacao", "prestigioso", "radiante",
        "memoravel", "efervescente", "conquista", "triumfo", "coragem",
        "gentileza", "resiliencia", "perspicaz", "enigma", "interessante",
        "incomparavel", "vibrante", "glorioso", "triunfante", "iluminado",
        "emocionante", "deslumbrante", "jovial", "lendario", "majestoso",
        "notavel", "ousado", "quixotesco", "radiante", "sublime",
        "transcendente", "inabalavel", "virtuoso", "zen", "extraordinario"
]

